<?php

/**
 * Catálogo B2B JobsHours para tienda online (commerce_store slug: jobshours).
 * Precios CLP referencia Araucanía 2026 (+ IVA si aplica).
 *
 * @see jobshours/INFORME-EMPRESARIAL-CATALOGO-JOBSHOURS-2026.md
 */
return [
    'store' => [
        'slug' => 'jobshours',
        'name' => 'JobsHours · Tienda digital',
        'primary_host' => 'tienda.jobshours.com',
        'host_aliases' => 'localhost,127.0.0.1,tienda.jobshours.local',
        'settings' => [
            'theme' => 'jobshours',
            'brand' => [
                'title' => 'JobsHours',
                'tagline' => 'Tu cliente pide y paga solo · Desde $29.990/mes · Instalación + mes 1: $109.990',
                'whatsapp' => '+56965133289',
                'support_hours' => 'Lun–Sáb 09:00–21:00',
                'region' => 'Araucanía, Chile',
            ],
            'links' => [
                'point_smart' => 'https://www.mercadopago.cl/point/smart',
                'point_mini' => 'https://www.mercadopago.cl/point',
                'mp_negocios' => 'https://www.mercadopago.cl/herramientas-para-vender',
                'tablet_guia_pdf' => '/docs/jh-tablet-recomendada.pdf',
            ],
            'catalog' => [
                'hide_internal_skus' => true,
                'internal_sku_prefix' => 'JH-INT-',
                'hide_category_slugs' => ['jh-enterprise', 'jh-interno'],
                'suggest_min_price' => 15000,
                'suggest_exclude_sku_prefixes' => ['JH-INT-', 'JH-HW-', 'JH-ENT-'],
            ],
            'destacados_skus' => [
                'JH-PKG-EXPRESS',
                'JH-PKG-FERIA',
                'JH-01',
                'JH-02',
            ],
            'checkout' => [
                'fulfillment_mode' => 'digital_service',
                'delivery_enabled' => false,
                'min_order_products' => 0,
                'packaging_default' => 'digital',
                'pickup_label' => 'Tus datos de contacto',
                'pickup_hint' => 'Tras el pago te escribimos por WhatsApp en 24 h para coordinar implementación (visita o remoto). No necesitas elegir fecha ahora.',
                'fecha_retiro_label' => 'Fecha preferida de inicio (opcional)',
            ],
        ],
    ],

    'categories' => [
        ['slug' => 'jh-planes', 'nombre' => 'Planes mensuales', 'sort' => 10],
        ['slug' => 'jh-paquetes', 'nombre' => 'Paquetes y configurador', 'sort' => 20],
        ['slug' => 'jh-implementacion', 'nombre' => 'Instalación (pago único)', 'sort' => 30],
        ['slug' => 'jh-servicios', 'nombre' => 'Servicios periféricos', 'sort' => 40],
        ['slug' => 'jh-addons', 'nombre' => 'Complementos', 'sort' => 50],
        ['slug' => 'jh-guias', 'nombre' => 'Guías hardware (cliente compra)', 'sort' => 60],
        ['slug' => 'jh-enterprise', 'nombre' => 'Enterprise · cotizar', 'sort' => 70],
        ['slug' => 'jh-interno', 'nombre' => 'Opciones internas', 'sort' => 99],
    ],

  /**
   * Productos visibles en catálogo. visibility=internal → solo bundle children.
   */
    'products' => [
        [
            'sku' => 'JH-CFG-AUTO',
            'nombre' => 'Arma tu paquete (avanzado)',
            'descripcion' => 'Para quien ya sabe qué necesita: plan + instalación + extras. Usa esto después de conocer las 2 ofertas principales.',
            'precio' => 0,
            'categoria' => 'jh-paquetes',
            'builder_profile' => 'jh_autoservicio',
            'es_pack' => false,
            'stock' => 999,
            'badge' => 'Avanzado',
        ],
        [
            'sku' => 'JH-PKG-FERIA',
            'nombre' => 'Te lo dejamos andando (instalación + mes 1)',
            'descripcion' => 'Instalación $80.000 + mes 1 $29.990 = $109.990 hoy. Tablet y maquinita Point no incluidas: las compras en MP o JobsHours te cotiza la maquinita aparte.',
            'precio' => 109990,
            'categoria' => 'jh-paquetes',
            'builder_profile' => 'jh_plan',
        ],
        [
            'sku' => 'JH-PKG-EXPRESS',
            'nombre' => 'Pack JobsHours Express (tablet + instalación + mes 1)',
            'descripcion' => 'Tablet de pedidos 10" + instalación + mes 1 por $199.990. No incluye maquinita Point (cobro tarjeta): compra en Mercado Pago, trae la tuya, o cotiza entrega con JobsHours aparte.',
            'precio' => 199990,
            'categoria' => 'jh-paquetes',
            'builder_profile' => 'jh_plan',
            'badge' => 'Recomendado',
        ],
        [
            'sku' => 'JH-01',
            'nombre' => 'Menos filas en el mostrador',
            'descripcion' => 'Pago de cada mes: programa en tablet de pedidos + soporte. Tu cliente pide y paga solo. Instalación (Mercado Pago, menú, visita) es aparte si no compras «Te lo dejamos andando».',
            'precio' => 29990,
            'categoria' => 'jh-planes',
            'builder_profile' => 'jh_plan',
            'precio_label' => '/mes',
        ],
        [
            'sku' => 'JH-02',
            'nombre' => 'Atiende WhatsApp mientras trabajas',
            'descripcion' => 'Todo lo anterior + respuestas automáticas en WhatsApp. Menos celular en hora punta.',
            'precio' => 44990,
            'categoria' => 'jh-planes',
            'builder_profile' => 'jh_plan',
            'precio_label' => '/mes',
        ],
        [
            'sku' => 'JH-03',
            'nombre' => 'Mostrador + tienda web',
            'descripcion' => 'Un solo inventario: vendes en local y por internet con Mercado Pago.',
            'precio' => 59990,
            'categoria' => 'jh-planes',
            'builder_profile' => 'jh_plan',
            'precio_label' => '/mes',
        ],
        [
            'sku' => 'JH-04',
            'nombre' => 'Caja minimarket',
            'descripcion' => 'Caja minimarket: inventario y varios usuarios. Lector de barras lo compras tú.',
            'precio' => 19990,
            'categoria' => 'jh-planes',
            'builder_profile' => 'jh_plan',
            'precio_label' => '/mes',
        ],
        [
            'sku' => 'JH-05',
            'nombre' => 'Restaurante Pro',
            'descripcion' => 'Mesas con código en celular, comanda cocina, salón. Precio según mix con tablet de pedidos — cotizar.',
            'precio' => 0,
            'stock' => 0,
            'cotizar_only' => true,
            'categoria' => 'jh-planes',
            'builder_profile' => 'jh_servicio',
            'precio_label' => 'Cotizar',
        ],
        [
            'sku' => 'JH-06',
            'nombre' => 'Diagnóstico digital 7 días',
            'descripcion' => 'Visita o remoto, prueba acotada e informe. Convierte a plan Autoservicio.',
            'precio' => 50000,
            'categoria' => 'jh-implementacion',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-IMP-100',
            'nombre' => 'Instalación básica · tú pones la tablet',
            'descripcion' => 'Visita o remoto: Mercado Pago + tablet de pedidos + menú + enseñanza 30 min.',
            'precio' => 100000,
            'categoria' => 'jh-implementacion',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-IMP-80',
            'nombre' => 'Instalación con visita (pago único)',
            'descripcion' => 'Una vez: Mercado Pago Negocios, menú ~20 ítems, maquinita o pago con celular, prueba de cobro y enseñanza ~30 min. No incluye pago de cada mes ni tablet.',
            'precio' => 80000,
            'categoria' => 'jh-implementacion',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-IMP-50',
            'nombre' => 'Solo administrativo Mercado Pago',
            'descripcion' => 'Cuenta Negocios, datos, abono y orientación comprobante.',
            'precio' => 50000,
            'categoria' => 'jh-implementacion',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-IMP-30',
            'nombre' => 'Solo activación · ya tienes equipo',
            'descripcion' => 'Software, menú e integración pagos. Sin visita completa.',
            'precio' => 30000,
            'categoria' => 'jh-implementacion',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-IMP-20',
            'nombre' => 'Capacitación adicional',
            'descripcion' => '30 minutos extra de capacitación en local o remoto.',
            'precio' => 20000,
            'categoria' => 'jh-implementacion',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-SRV-CERT',
            'nombre' => 'Certificación empresa (inicio tributario)',
            'descripcion' => 'Orientación y checklist para constituir/regularizar empresa antes de MP y boletas. No reemplaza contador.',
            'precio' => 120000,
            'categoria' => 'jh-servicios',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-SRV-DTE-MP',
            'nombre' => 'Registro boleta electrónica Mercado Pago',
            'descripcion' => 'Alta y configuración inicial de emisión según lo habilitado en MP para el cliente. Alcance según producto MP vigente.',
            'precio' => 180000,
            'categoria' => 'jh-servicios',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-SRV-BOT-IMP',
            'nombre' => 'Implementación agente IA WhatsApp',
            'descripcion' => 'Configuración bot, personalidad, horarios y catálogo en chat (sin plan mensual incluido).',
            'precio' => 80000,
            'categoria' => 'jh-servicios',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-SRV-MANT',
            'nombre' => 'Mantención mensual estándar',
            'descripcion' => 'Revisión remota, ajustes menú y monitoreo básico. Hasta 1 h/mes.',
            'precio' => 19990,
            'categoria' => 'jh-servicios',
            'builder_profile' => 'jh_servicio',
            'precio_label' => '/mes',
        ],
        [
            'sku' => 'JH-ADD-BOT',
            'nombre' => 'Add-on Bot IA (sin cambiar plan base)',
            'descripcion' => 'Suma bot a plan kiosko existente.',
            'precio' => 15000,
            'categoria' => 'jh-addons',
            'builder_profile' => 'jh_servicio',
            'precio_label' => '/mes',
        ],
        [
            'sku' => 'JH-ADD-SOP',
            'nombre' => 'Soporte prioritario',
            'descripcion' => 'Cola preferente Lun–Sáb 09:00–21:00.',
            'precio' => 9990,
            'categoria' => 'jh-addons',
            'builder_profile' => 'jh_servicio',
            'precio_label' => '/mes',
        ],
        [
            'sku' => 'JH-ADD-MENU',
            'nombre' => 'Menú +20 productos',
            'descripcion' => 'Carga y organización de 20 ítems adicionales en menú.',
            'precio' => 20000,
            'categoria' => 'jh-addons',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-HW-POINT-S',
            'nombre' => 'Guía Point Smart',
            'descripcion' => 'Guía para comprar Point Smart en Mercado Pago. JobsHours también puede entregar/revender con precio aparte acordado.',
            'precio' => 0,
            'categoria' => 'jh-guias',
            'builder_profile' => 'jh_guia',
        ],
        [
            'sku' => 'JH-HW-POINT-M',
            'nombre' => 'Guía Point Mini',
            'descripcion' => 'Guía Point Mini. O cotiza entrega con JobsHours (precio hardware aparte del programa).',
            'precio' => 0,
            'categoria' => 'jh-guias',
            'builder_profile' => 'jh_guia',
        ],
        [
            'sku' => 'JH-HW-TAB',
            'nombre' => 'Ficha tablet recomendada',
            'descripcion' => 'PDF modelos 10", ≥3 GB RAM. Compra en retail por cuenta del cliente.',
            'precio' => 0,
            'categoria' => 'jh-guias',
            'builder_profile' => 'jh_guia',
        ],
        [
            'sku' => 'JH-HW-PC',
            'nombre' => 'Uso PC existente',
            'descripcion' => 'Requisitos: Chrome actualizado y Wi‑Fi estable.',
            'precio' => 0,
            'categoria' => 'jh-guias',
            'builder_profile' => 'jh_guia',
        ],
        [
            'sku' => 'JH-ENT-MAP',
            'nombre' => 'JobsHours Local Connect',
            'descripcion' => 'Mapa comercio + inventario multi-sucursal. Proyecto enterprise.',
            'precio' => 2500000,
            'categoria' => 'jh-enterprise',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-ENT-OBRA',
            'nombre' => 'ObraControl / Campo Seguro',
            'descripcion' => 'Control faena y personal en obra.',
            'precio' => 1500000,
            'categoria' => 'jh-enterprise',
            'builder_profile' => 'jh_servicio',
        ],
        [
            'sku' => 'JH-DTE',
            'nombre' => 'Pagos Pro + DTE (evolución)',
            'descripcion' => 'Emisión avanzada según alcance técnico acordado. Cotizar.',
            'precio' => 350000,
            'categoria' => 'jh-enterprise',
            'builder_profile' => 'jh_servicio',
        ],
    ],

    'internal_products' => [
        ['sku' => 'JH-INT-MRR-29990', 'nombre' => 'Plan mensual · Kiosko $29.990', 'precio' => 29990, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-MRR-44990', 'nombre' => 'Plan mensual · Kiosko + IA $44.990', 'precio' => 44990, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-MRR-59990', 'nombre' => 'Plan mensual · Omnicanal $59.990', 'precio' => 59990, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-IMP-100', 'nombre' => 'Implementación completa · visita + capacitación · $100.000', 'precio' => 100000, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-IMP-80', 'nombre' => 'Implementación feria · visita + capacitación · $80.000', 'precio' => 80000, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-IMP-50', 'nombre' => 'Solo administrativo Mercado Pago · $50.000', 'precio' => 50000, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-IMP-30', 'nombre' => 'Solo activación software · ya tengo tablet y Point · $30.000', 'precio' => 30000, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-IMP-0', 'nombre' => 'Sin implementación · solo activo el plan', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-HW-POINT-OWN', 'nombre' => 'Ya tengo Point · sin cargo extra', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-HW-POINT-S', 'nombre' => 'Compraré Point Smart (link MP)', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-HW-POINT-M', 'nombre' => 'Compraré Point Mini (link MP)', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-HW-POINT-ASESOR', 'nombre' => 'Necesito asesoría para elegir Point', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-HW-TAB-OWN', 'nombre' => 'Uso mi tablet · sin cargo extra', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-HW-TAB-BUY', 'nombre' => 'Compraré tablet (ver guía PDF)', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-HW-PC', 'nombre' => 'Uso mi PC · sin cargo extra', 'precio' => 0, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-ADD-CAP', 'nombre' => 'Capacitación extra 30 min', 'precio' => 20000, 'categoria' => 'jh-interno'],
        ['sku' => 'JH-INT-ADD-MENU20', 'nombre' => '+20 productos menú', 'precio' => 20000, 'categoria' => 'jh-interno'],
    ],

    'configurators' => [
        [
            'parent_sku' => 'JH-CFG-AUTO',
            'customization_fields' => [
                ['key' => 'negocio_nombre', 'label' => 'Nombre del negocio', 'type' => 'text', 'required' => true],
                ['key' => 'whatsapp', 'label' => 'WhatsApp de contacto', 'type' => 'text', 'required' => true],
                ['key' => 'comuna', 'label' => 'Comuna / ciudad', 'type' => 'text', 'required' => true],
                ['key' => 'notas', 'label' => 'Notas para implementación', 'type' => 'textarea', 'required' => false],
            ],
            'bundles' => [
                [
                    'group' => 'Plan mensual (primer mes en carrito)',
                    'input_type' => 'radio',
                    'required' => true,
                    'sort' => 10,
                    'options' => [
                        ['sku' => 'JH-INT-MRR-29990', 'price_modifier' => 29990],
                        ['sku' => 'JH-INT-MRR-44990', 'price_modifier' => 44990],
                        ['sku' => 'JH-INT-MRR-59990', 'price_modifier' => 59990],
                    ],
                ],
                [
                    'group' => 'Implementación (pago único)',
                    'input_type' => 'radio',
                    'required' => true,
                    'sort' => 20,
                    'options' => [
                        ['sku' => 'JH-INT-IMP-0', 'price_modifier' => 0],
                        ['sku' => 'JH-INT-IMP-30', 'price_modifier' => 30000],
                        ['sku' => 'JH-INT-IMP-50', 'price_modifier' => 50000],
                        ['sku' => 'JH-INT-IMP-80', 'price_modifier' => 80000],
                        ['sku' => 'JH-INT-IMP-100', 'price_modifier' => 100000],
                    ],
                ],
                [
                    'group' => 'Complementos opcionales',
                    'input_type' => 'checkbox',
                    'required' => false,
                    'sort' => 30,
                    'options' => [
                        ['sku' => 'JH-INT-ADD-CAP', 'price_modifier' => 20000],
                        ['sku' => 'JH-INT-ADD-MENU20', 'price_modifier' => 20000],
                    ],
                ],
                [
                    'group' => 'Terminal Mercado Pago (opcional)',
                    'input_type' => 'radio',
                    'required' => false,
                    'sort' => 40,
                    'options' => [
                        ['sku' => 'JH-INT-HW-POINT-OWN', 'price_modifier' => 0],
                        ['sku' => 'JH-INT-HW-POINT-S', 'price_modifier' => 0],
                        ['sku' => 'JH-INT-HW-POINT-M', 'price_modifier' => 0],
                        ['sku' => 'JH-INT-HW-POINT-ASESOR', 'price_modifier' => 0],
                    ],
                ],
                [
                    'group' => 'Pantalla en local (opcional)',
                    'input_type' => 'radio',
                    'required' => false,
                    'sort' => 50,
                    'options' => [
                        ['sku' => 'JH-INT-HW-TAB-OWN', 'price_modifier' => 0],
                        ['sku' => 'JH-INT-HW-TAB-BUY', 'price_modifier' => 0],
                        ['sku' => 'JH-INT-HW-PC', 'price_modifier' => 0],
                    ],
                ],
            ],
        ],
    ],

    'packaging_digital' => [
        'digital' => [
            'label' => 'Servicio digital · sin envío físico',
            'description' => 'Coordinamos implementación por WhatsApp tras confirmar el pago.',
            'amount' => 0,
            'barcode' => 'JH-PACK-DIGITAL',
        ],
    ],
];
