<?php

/**
 * Tarjetas premium web — contenido visual por pack cerrado.
 * `nombre` debe coincidir con el producto pack en inventario.
 */
return [
    'title' => 'Packs regalo',
    'tagline' => 'Contenido fijo · lo que ves es lo que recibes',
    'dia_padre' => [
        'activo' => true,
        'fecha' => '2026-06-19',
        'fecha_label' => 'Retiro 19 de junio · Día del Padre',
        'headline' => 'Sorprende a papá con un pack regalo completo',
        'subheadline' => 'Contenido fijo · envío gratis en Renaico · retiro Santiago Watt 205, Renaico',
    ],

    'dia_padre_comida' => [
        'activo' => true,
        'fecha' => '2026-06-19',
        'fecha_label' => 'Retiro 19 de junio · Cocina a pedido',
        'headline' => 'Combos cocina Papá — hechos para tu fecha',
        'subheadline' => 'Reserva online · precio fijo · lo preparamos el día de retiro en Santiago Watt 205, Renaico',
    ],

    /** Ranking Facebook Angol/Renaico — preparado vs para preparar */
    'cocina_casa_facebook' => [
        'activo' => true,
        'fecha_label' => 'Lo más pedido en Facebook · Renaico',
        'headline' => 'Cocina de la casa — listo o para cocinar',
        'subheadline' => 'Basado en los 100 platos más vendidos en Facebook de la zona. Paga en dondemorales.cl · retiro Santiago Watt 205, Renaico · ideal para publicar en redes.',
        'whatsapp_cta' => 'https://wa.me/56975647756?text=Hola%2C%20vi%20los%20packs%20Cocina%20de%20la%20casa%20en%20dondemorales.cl',
    ],

    'tarjetas' => [
        [
            'nombre' => 'Pack Papá Completo',
            'coleccion' => 'dia_padre',
            'badge' => 'Día del Padre',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Desayuno completo con palta · 13 ítems',
            'accent' => 'slate',
            'gradient' => 'from-slate-900 via-blue-950 to-indigo-950',
            'imagen' => '/images/regalos/pack-papa-completo.png',
            'items_visual' => [
                ['icon' => 'empaque', 'label' => 'Caja regalo con visor + papel seda + cinta', 'tipo' => 'empaque'],
                ['icon' => 'tarjeta', 'label' => 'Tarjeta Feliz día papá + sticker DondeMorales', 'tipo' => 'empaque'],
                ['icon' => 'pan', 'label' => '4 marraquetas frescas', 'tipo' => 'producto'],
                ['icon' => 'cafe', 'label' => 'Café Nescafé 50 g + té de bolsa', 'tipo' => 'producto'],
                ['icon' => 'jamon', 'label' => 'Jamón y queso laminados 200 g (envases plásticos al vacío)', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Palta lista 150 g en envase plástico', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => '1 muffin artesanal', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Galletas dulces surtidas', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Maní salado', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Pack Papá Premium',
            'coleccion' => 'dia_padre',
            'spotlight' => true,
            'badge' => 'Más vendido',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Completo + palta + Ferrero + globo + postre · 17 ítems',
            'accent' => 'amber',
            'gradient' => 'from-amber-950 via-orange-950 to-slate-950',
            'imagen' => '/images/regalos/pack-papa-premium.png',
            'items_visual' => [
                ['icon' => 'empaque', 'label' => 'Caja regalo con visor + seda + cinta + tarjeta', 'tipo' => 'empaque'],
                ['icon' => 'pan', 'label' => '4 marraquetas frescas', 'tipo' => 'producto'],
                ['icon' => 'cafe', 'label' => 'Café Nescafé 50 g + té de bolsa', 'tipo' => 'producto'],
                ['icon' => 'jamon', 'label' => 'Jamón y queso laminados 200 g (envases plásticos al vacío)', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Palta lista 150 g en envase plástico', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Muffin artesanal + galletas dulces + maní salado', 'tipo' => 'producto'],
                ['icon' => 'chocolate', 'label' => 'Ferrero Rocher 8 unidades', 'tipo' => 'producto'],
                ['icon' => 'globo', 'label' => 'Globo metálico Día del Padre', 'tipo' => 'empaque'],
                ['icon' => 'dulce', 'label' => 'Postre / queque individual', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Pack Papá Bandeja',
            'coleccion' => 'dia_padre',
            'badge' => 'Bandeja',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Canasto + picoteo salado · 18 ítems',
            'accent' => 'emerald',
            'gradient' => 'from-emerald-950 via-teal-950 to-slate-950',
            'imagen' => '/images/regalos/pack-papa-bandeja.png',
            'items_visual' => [
                ['icon' => 'canasto', 'label' => 'Canasto mimbre M + viruta + papel seda + cinta', 'tipo' => 'empaque'],
                ['icon' => 'globo', 'label' => 'Globo metálico Día del Padre', 'tipo' => 'empaque'],
                ['icon' => 'pan', 'label' => '4 marraquetas frescas', 'tipo' => 'producto'],
                ['icon' => 'jamon', 'label' => 'Jamón y queso laminados al vacío', 'tipo' => 'producto'],
                ['icon' => 'cafe', 'label' => 'Café Nescafé + té de bolsa', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Picoteo: salame, crackers, aceitunas y maní', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Yogurt + 2 muffins + galletas dulces', 'tipo' => 'producto'],
                ['icon' => 'tarjeta', 'label' => 'Tarjeta Feliz día papá + sticker DondeMorales', 'tipo' => 'empaque'],
            ],
        ],

        // —— Combos cocina Día del Padre (a pedido) ——
        [
            'nombre' => 'Combo Papá Cena Premium',
            'coleccion' => 'dia_padre_comida',
            'spotlight' => true,
            'badge' => 'Estrella',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Chorrillana XL + vino + 2 copas helado',
            'accent' => 'red',
            'gradient' => 'from-red-950 via-rose-950 to-amber-950',
            'imagen' => '/images/comida/combo-papa-cena-premium.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'snack', 'label' => 'Chorrillana XL clásica', 'tipo' => 'producto'],
                ['icon' => 'espumante', 'label' => 'Vino tinto 375 ml', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => '2 copas yogurt Toppi\'s a elección', 'tipo' => 'producto'],
                ['icon' => 'empaque', 'label' => 'Cocina a pedido · retiro 19 jun', 'tipo' => 'empaque'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Chorrillana + Helado',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Para compartir',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Chorrillana + jugo + copa postre',
            'accent' => 'orange',
            'gradient' => 'from-red-950 via-orange-950 to-slate-950',
            'imagen' => '/images/comida/combo-papa-chorrillana.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'snack', 'label' => 'Chorrillana compartir clásica', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Copa yogurt Toppi\'s a elección', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Sushi',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Sushi',
            'badge_fecha' => '19 JUN',
            'tagline' => '40 piezas mix + jugo + postre',
            'accent' => 'emerald',
            'gradient' => 'from-emerald-950 via-teal-950 to-slate-950',
            'imagen' => '/images/comida/combo-papa-sushi.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'snack', 'label' => 'Sushi mix 40 piezas', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Copa helado yogurt opcional', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Mechada Chilena',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Chileno',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Mechada + marraquetas + jugo',
            'accent' => 'amber',
            'gradient' => 'from-amber-950 via-orange-950 to-red-950',
            'imagen' => '/images/comida/combo-papa-mechada.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'jamon', 'label' => 'Carne mechada 600 g', 'tipo' => 'producto'],
                ['icon' => 'pan', 'label' => '4 marraquetas frescas', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Pollo Asado',
            'coleccion' => 'dia_padre_comida',
            'badge' => '4 personas',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Pollo asado + ensalada + jugo',
            'accent' => 'slate',
            'gradient' => 'from-amber-950 via-yellow-950 to-orange-950',
            'imagen' => '/images/comida/combo-papa-pollo.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'snack', 'label' => 'Pollo asado entero', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Ensalada chilena', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Pizza Familiar',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Pizza',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Pizza 2 sabores + bebida 2 L',
            'accent' => 'rose',
            'gradient' => 'from-rose-950 via-red-950 to-orange-950',
            'imagen' => '/images/comida/combo-papa-pizza.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'snack', 'label' => 'Pizza familiar 2 sabores', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 2 L', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Fajitas Mexicanas',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Mexicano',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Fajitas + guacamole + 2 jugos',
            'accent' => 'violet',
            'gradient' => 'from-lime-950 via-emerald-950 to-teal-950',
            'imagen' => '/images/comida/combo-papa-fajitas.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'snack', 'label' => 'Fajitas de pollo', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Guacamole fresco', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => '2 jugos naturales', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Completos',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Clásico',
            'badge_fecha' => '19 JUN',
            'tagline' => '2 completos italianos + 2 jugos',
            'accent' => 'amber',
            'gradient' => 'from-yellow-950 via-amber-950 to-orange-950',
            'imagen' => '/images/comida/combo-papa-completos.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'pan', 'label' => '2 completos italianos', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => '2 jugos naturales', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Churrascos',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Churrasco',
            'badge_fecha' => '19 JUN',
            'tagline' => '2 churrascos + 2 jugos',
            'accent' => 'slate',
            'gradient' => 'from-stone-900 via-amber-950 to-orange-950',
            'imagen' => '/images/comida/combo-papa-churrascos.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'jamon', 'label' => '2 churrascos clásicos', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => '2 jugos naturales', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Combo Papá Sándwiches premium',
            'coleccion' => 'dia_padre_comida',
            'badge' => 'Premium',
            'badge_fecha' => '19 JUN',
            'tagline' => 'Doble piso + Preinfarto + 2 jugos',
            'accent' => 'red',
            'gradient' => 'from-zinc-950 via-red-950 to-orange-950',
            'imagen' => '/images/comida/combo-papa-churrascos.png',
            'a_pedido' => true,
            'items_visual' => [
                ['icon' => 'jamon', 'label' => 'Sándwich doble piso', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Preinfarto', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => '2 jugos naturales', 'tipo' => 'producto'],
            ],
        ],

        [
            'nombre' => 'Pack Desayuno Clásico',
            'badge' => 'Regalo',
            'ocasion' => 'desayuno',
            'tagline' => 'Desayuno armado con cariño',
            'accent' => 'rose',
            'gradient' => 'from-rose-950 via-pink-950 to-violet-950',
            'imagen' => '/images/regalos/pack-desayuno-clasico.png',
            'items_visual' => [
                ['icon' => 'pan', 'label' => '4 marraquetas frescas', 'tipo' => 'producto'],
                ['icon' => 'cafe', 'label' => 'Café Nescafé 50 g', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Mermelada individual', 'tipo' => 'producto'],
                ['icon' => 'empaque', 'label' => 'Caja regalo con visor', 'tipo' => 'empaque'],
                ['icon' => 'seda', 'label' => 'Papel seda', 'tipo' => 'empaque'],
                ['icon' => 'cinta', 'label' => 'Cinta + tarjeta + sticker', 'tipo' => 'empaque'],
            ],
        ],
        [
            'nombre' => 'Pack Cumpleaños para Mamá',
            'badge' => 'Para mamá',
            'ocasion' => 'para_mama',
            'tagline' => 'Cumpleaños o “solo porque”',
            'accent' => 'pink',
            'gradient' => 'from-pink-950 via-rose-950 to-violet-950',
            'imagen' => '/images/regalos/pack-cumpleanos-dulce.png',
            'items_visual' => [
                ['icon' => 'globo', 'label' => 'Globo metálico', 'tipo' => 'producto'],
                ['icon' => 'chocolate', 'label' => 'Ferrero Rocher 8 u.', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo 1 L + té', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Muffin + galletas', 'tipo' => 'producto'],
                ['icon' => 'empaque', 'label' => 'Caja regalo + tarjeta', 'tipo' => 'empaque'],
            ],
        ],
        [
            'nombre' => 'Pack Cumpleaños Dulce',
            'badge' => 'Cumpleaños',
            'ocasion' => 'cumpleanos',
            'tagline' => 'Festivo y listo para sorprender',
            'accent' => 'violet',
            'gradient' => 'from-fuchsia-950 via-purple-950 to-violet-950',
            'imagen' => '/images/regalos/pack-cumpleanos-dulce.png',
            'items_visual' => [
                ['icon' => 'globo', 'label' => 'Globo metálico con vara', 'tipo' => 'empaque'],
                ['icon' => 'chocolate', 'label' => 'Ferrero Rocher 8 u.', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo natural 1 L', 'tipo' => 'producto'],
                ['icon' => 'dulce', 'label' => 'Galletas surtidas', 'tipo' => 'producto'],
                ['icon' => 'empaque', 'label' => 'Caja regalo + cinta', 'tipo' => 'empaque'],
                ['icon' => 'tarjeta', 'label' => 'Tarjeta + sticker', 'tipo' => 'empaque'],
            ],
        ],
        [
            'nombre' => 'Pack Amor & Espumante',
            'badge' => 'Amor',
            'ocasion' => 'amor',
            'tagline' => 'Detalle romántico premium',
            'accent' => 'rose',
            'gradient' => 'from-rose-950 via-red-950 to-pink-950',
            'imagen' => '/images/regalos/pack-amor-espumante.png',
            'items_visual' => [
                ['icon' => 'espumante', 'label' => 'Espumante 375 ml', 'tipo' => 'producto'],
                ['icon' => 'chocolate', 'label' => 'Ferrero Rocher 8 u.', 'tipo' => 'producto'],
                ['icon' => 'snack', 'label' => 'Mix frutos secos', 'tipo' => 'producto'],
                ['icon' => 'mug', 'label' => 'Mug decorativo', 'tipo' => 'empaque'],
                ['icon' => 'empaque', 'label' => 'Caja + seda + cinta', 'tipo' => 'empaque'],
            ],
        ],
        [
            'nombre' => 'Pack Once Familiar',
            'badge' => 'Once',
            'ocasion' => 'once',
            'tagline' => 'Para compartir en familia',
            'accent' => 'amber',
            'gradient' => 'from-amber-950 via-orange-950 to-rose-950',
            'imagen' => '/images/regalos/pack-once-familiar.png',
            'items_visual' => [
                ['icon' => 'canasto', 'label' => 'Canasto mimbre M', 'tipo' => 'empaque'],
                ['icon' => 'pan', 'label' => '4 marraquetas', 'tipo' => 'producto'],
                ['icon' => 'jamon', 'label' => 'Jamón laminado 200 g', 'tipo' => 'producto'],
                ['icon' => 'queso', 'label' => 'Queso gauda 200 g', 'tipo' => 'producto'],
                ['icon' => 'cracker', 'label' => 'Galletas crackers', 'tipo' => 'producto'],
                ['icon' => 'bebida', 'label' => 'Jugo + té', 'tipo' => 'producto'],
                ['icon' => 'seda', 'label' => 'Viruta + seda + cinta', 'tipo' => 'empaque'],
            ],
        ],
        [
            'nombre' => 'Pack Condolencias / Té',
            'badge' => 'Condolencias',
            'ocasion' => 'condolencias',
            'tagline' => 'Detalle sobrio y respetuoso',
            'accent' => 'slate',
            'gradient' => 'from-stone-900 via-slate-900 to-zinc-950',
            'imagen' => '/images/regalos/pack-condolencias.png',
            'items_visual' => [
                ['icon' => 'te', 'label' => 'Té de especialidad', 'tipo' => 'producto'],
                ['icon' => 'cracker', 'label' => 'Galletas crackers', 'tipo' => 'producto'],
                ['icon' => 'tarjeta', 'label' => 'Tarjeta de saludo', 'tipo' => 'empaque'],
                ['icon' => 'bolsa', 'label' => 'Bolsa kraft + cordón', 'tipo' => 'empaque'],
            ],
        ],
        [
            'nombre' => 'Pack Corporativo (B2B)',
            'badge' => 'Empresa',
            'ocasion' => 'corporativo',
            'tagline' => 'Mínimo 10 unidades',
            'accent' => 'emerald',
            'gradient' => 'from-emerald-950 via-teal-950 to-slate-950',
            'imagen' => '/images/regalos/pack-corporativo.png',
            'items_visual' => [
                ['icon' => 'cafe', 'label' => 'Café Nescafé 50 g', 'tipo' => 'producto'],
                ['icon' => 'cracker', 'label' => 'Galletas crackers', 'tipo' => 'producto'],
                ['icon' => 'tarjeta', 'label' => 'Tarjeta corporativa', 'tipo' => 'empaque'],
                ['icon' => 'bolsa', 'label' => 'Bolsa kraft + sticker', 'tipo' => 'empaque'],
            ],
        ],

        // —— Cocina de la casa · ranking Facebook zona (jun 2026) ——
        [
            'nombre' => 'Pack Kit Cazuela Completa DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'spotlight' => true,
            'badge' => 'Top Facebook #1',
            'badge_fecha' => 'PARA COCINAR',
            'tagline' => 'Verduras + vacuno + condimento · 98% popularidad zona',
            'accent' => 'emerald',
            'gradient' => 'from-emerald-950 via-green-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'verdura', 'label' => 'Papa, zapallo, zanahoria, cebolla, ají y choclo', 'tipo' => 'producto'],
                ['icon' => 'carne', 'label' => 'Plateada vacuno 400 g', 'tipo' => 'producto'],
                ['icon' => 'condimento', 'label' => 'Base condimento + tarjeta receta 30 min', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Cazuela Vacuno Lista DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Top Facebook #1',
            'badge_fecha' => 'LISTO',
            'tagline' => 'Calienta y come · elaboración del día',
            'accent' => 'emerald',
            'gradient' => 'from-teal-950 via-emerald-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'plato', 'label' => 'Cazuela vacuno 1 porción lista', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Pack Kit Cazuela Verduras DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Kit verduras',
            'badge_fecha' => 'PARA COCINAR',
            'tagline' => 'Solo verduras + condimento · tú agregas la carne',
            'accent' => 'lime',
            'gradient' => 'from-lime-950 via-green-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'verdura', 'label' => 'Verduras picadas para cazuela', 'tipo' => 'producto'],
                ['icon' => 'condimento', 'label' => 'Condimento + receta', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Pack Kit Pastel de Choclo DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Top Facebook #2',
            'badge_fecha' => 'PARA COCINAR',
            'tagline' => 'Choclo, pino, huevos y aliño · horno en casa',
            'accent' => 'amber',
            'gradient' => 'from-amber-950 via-yellow-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'choclo', 'label' => 'Choclo molido + pino + huevos', 'tipo' => 'producto'],
                ['icon' => 'condimento', 'label' => 'Base aliño pastel', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Pastel de Choclo Listo DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Top Facebook #2',
            'badge_fecha' => 'LISTO',
            'tagline' => 'Clásico chileno listo para calentar',
            'accent' => 'amber',
            'gradient' => 'from-orange-950 via-amber-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'plato', 'label' => 'Pastel de choclo 1 porción', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Pack Kit Charquicán Casero DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Top Facebook #5',
            'badge_fecha' => 'PARA COCINAR',
            'tagline' => 'Papa, zapallo, carne molida y merkén',
            'accent' => 'orange',
            'gradient' => 'from-orange-950 via-red-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'verdura', 'label' => 'Papa, zapallo y cebolla', 'tipo' => 'producto'],
                ['icon' => 'carne', 'label' => 'Carne molida 400 g', 'tipo' => 'producto'],
                ['icon' => 'condimento', 'label' => 'Base merkén', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Charquicán Listo DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Top Facebook #5',
            'badge_fecha' => 'LISTO',
            'tagline' => 'Guiso sureño · porción individual',
            'accent' => 'orange',
            'gradient' => 'from-red-950 via-orange-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'plato', 'label' => 'Charquicán 1 porción lista', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Pack Kit Porotos con Riendas DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Top Facebook #6',
            'badge_fecha' => 'PARA COCINAR',
            'tagline' => 'Porotos, zapallo, tallarines y longaniza',
            'accent' => 'teal',
            'gradient' => 'from-teal-950 via-cyan-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'verdura', 'label' => 'Porotos verdes + zapallo', 'tipo' => 'producto'],
                ['icon' => 'fideo', 'label' => 'Tallarines + longaniza', 'tipo' => 'producto'],
            ],
        ],
        [
            'nombre' => 'Porotos con Riendas Listo DondeMorales',
            'coleccion' => 'cocina_casa_facebook',
            'badge' => 'Top Facebook #6',
            'badge_fecha' => 'LISTO',
            'tagline' => 'Plato típico · calienta y sirve',
            'accent' => 'teal',
            'gradient' => 'from-cyan-950 via-teal-900 to-slate-950',
            'items_visual' => [
                ['icon' => 'plato', 'label' => 'Porotos con riendas 1 porción', 'tipo' => 'producto'],
            ],
        ],
    ],
];
