<?php

/**
 * Canastas, combos y reservas — /packs en dondemorales.cl
 * `nombre` = clave BD (PackCreationService). `nombre_publico` = lo que ve el cliente.
 */
return [
    'title' => 'Canastas, combos y reservas',
    'tagline' => 'Personaliza online · pagamos juntos · lo armamos para tu retiro',
    'subtitle' => 'Elige productos reales del minimarket y Toppi\'s. Pago online = reserva confirmada en Santiago Watt 205, Renaico.',

    'flujo' => [
        ['paso' => 1, 'titulo' => 'Elige y personaliza', 'texto' => 'Marca opciones (radio o extras) — ves el precio final'],
        ['paso' => 2, 'titulo' => 'Reserva y paga', 'texto' => 'Fecha de retiro + Mercado Pago o Flow'],
        ['paso' => 3, 'titulo' => 'Lo armamos', 'texto' => 'Descontamos stock de cada producto suelto antes de tu llegada'],
    ],

    /** Combos prediseñados — atajo 1 clic desde sección helados (nombre = clave BD) */
    'helados_listos' => [
        [
            'nombre' => 'Copa Crunchy Biscoff Toppi\'s',
            'nombre_publico' => 'Copa Biscoff',
            'badge' => 'Best seller',
            'descripcion_corta' => 'Yogurt + speculoos y caramelo — listo, sin armar.',
            'imagen' => '/images/helados/copa-biscoff.png',
        ],
        [
            'nombre' => 'ChocoBomba Frutal',
            'nombre_publico' => 'ChocoBomba',
            'badge' => 'Top',
            'descripcion_corta' => 'Yogurt frutilla + chocolate + galleta — precio fijo.',
            'imagen' => '/images/helados/chocobomba.png',
        ],
        [
            'nombre' => 'Copa Cheesecake Berries Toppi\'s',
            'nombre_publico' => 'Copa Berries',
            'badge' => 'Instagram',
            'descripcion_corta' => 'Frutillas, arándanos y salsa frutos rojos.',
            'imagen' => '/images/helados/copa-berries.png',
        ],
        [
            'nombre' => 'Copa Antioxidante Tropical Toppi\'s',
            'nombre_publico' => 'Copa Tropical',
            'badge' => 'Fresco',
            'descripcion_corta' => 'Mango, kiwi, granola y miel.',
            'imagen' => '/images/helados/copa-tropical.png',
        ],
    ],

    'confianza' => [
        ['icon' => 'shield', 'texto' => 'Pago seguro Mercado Pago / Flow'],
        ['icon' => 'calendar', 'texto' => 'Reserva con 24 h — lo armamos antes de tu retiro'],
        ['icon' => 'gift', 'texto' => 'Tarjeta de saludo en canastas regalo · imagen referencial'],
        ['icon' => 'truck', 'texto' => 'Envío gratis packs regalo en Renaico'],
    ],

    /** Packs regalo cerrados — 1 clic al carrito (contenido fijo) */
    'regalos_cerrados' => [
        [
            'nombre' => 'Pack Desayuno Clásico',
            'nombre_publico' => 'Desayuno clásico',
            'badge' => 'Cerrado',
            'ocasion' => 'desayuno',
            'descripcion_corta' => 'Marraquetas, café, mermelada y empaque completo — sin elegir.',
            'imagen' => '/images/regalos/pack-desayuno-clasico.png',
        ],
        [
            'nombre' => 'Pack Cumpleaños para Mamá',
            'nombre_publico' => 'Cumpleaños para mamá',
            'badge' => 'Estrella',
            'ocasion' => 'para_mama',
            'descripcion_corta' => 'Globo + Ferrero + jugo, té y muffin — empaque regalo fijo.',
            'imagen' => '/images/regalos/pack-cumpleanos-dulce.png',
        ],
        [
            'nombre' => 'Pack Cumpleaños Dulce',
            'nombre_publico' => 'Cumpleaños dulce',
            'badge' => 'Cerrado',
            'ocasion' => 'cumpleanos',
            'descripcion_corta' => 'Globo + Ferrero + jugo + empaque festivo fijo.',
            'imagen' => '/images/regalos/pack-cumpleanos-dulce.png',
        ],
        [
            'nombre' => 'Pack Corporativo (B2B)',
            'nombre_publico' => 'Corporativo B2B',
            'badge' => 'Empresa',
            'ocasion' => 'corporativo',
            'descripcion_corta' => 'Café + galletas + bolsa kraft — mínimo 10 unidades.',
            'imagen' => '/images/regalos/pack-corporativo.png',
        ],
        [
            'nombre' => 'Pack Amor & Espumante',
            'nombre_publico' => 'Amor & espumante',
            'badge' => 'Cerrado',
            'ocasion' => 'amor',
            'descripcion_corta' => 'Espumante + chocolates + detalle romántico fijo.',
            'imagen' => '/images/regalos/pack-amor-espumante.png',
        ],
        [
            'nombre' => 'Pack Once Familiar',
            'nombre_publico' => 'Once familiar',
            'badge' => 'Cerrado',
            'ocasion' => 'once',
            'descripcion_corta' => 'Canasto + salados y dulces — lista fija.',
            'imagen' => '/images/regalos/pack-once-familiar.png',
        ],
    ],

    'secciones' => [
        [
            'id' => 'helados',
            'titulo' => 'Helados Toppi\'s',
            'subtitulo' => 'Arma tu helado — base yogurt, soft o artesanal + toppings del inventario',
            'gradient' => 'from-fuchsia-900/90 via-violet-950/80 to-slate-950/70',
            'items' => [
                [
                    'nombre' => 'Arma tu Yogurt Toppi\'s',
                    'nombre_publico' => 'Arma tu helado de yogurt',
                    'modalidad_label' => 'Personalizable · elige 1 por grupo',
                    'badge' => 'Yogurt',
                    'descripcion_corta' => 'Sabor de yogurt + tamaño de copa + toppings y salsas a elección.',
                    'gradient' => 'from-emerald-800/90 via-teal-900/80 to-cyan-950/70',
                    'imagen' => '/images/helados/yogen-mix.png',
                ],
                [
                    'nombre' => 'Arma tu Soft Toppi\'s',
                    'nombre_publico' => 'Arma tu helado soft',
                    'modalidad_label' => 'Personalizable · elige 1 por grupo',
                    'badge' => 'Soft',
                    'descripcion_corta' => 'Soft cremoso + toppings opcionales del catálogo Toppi\'s.',
                    'gradient' => 'from-slate-700/90 via-slate-900/80 to-zinc-950/70',
                    'imagen' => '/images/helados/copa-biscoff.png',
                ],
                [
                    'nombre' => 'Arma tu Artesanal Toppi\'s',
                    'nombre_publico' => 'Arma tu helado artesanal',
                    'modalidad_label' => 'Personalizable · elige 1 por grupo',
                    'badge' => 'Premium',
                    'descripcion_corta' => 'Sabores artesanales + extras premium a elección.',
                    'gradient' => 'from-amber-800/90 via-orange-900/80 to-rose-950/70',
                    'imagen' => '/images/helados/chocobomba.png',
                ],
                [
                    'nombre' => 'Combo Helado + Bebida',
                    'nombre_publico' => 'Combo helado + bebida',
                    'modalidad_label' => 'Combo · elige base y bebida',
                    'badge' => 'Combo',
                    'descripcion_corta' => 'Helado (yogurt, soft o artesanal) + bebida incluida — tú eliges cada parte.',
                    'gradient' => 'from-fuchsia-800/90 via-pink-900/80 to-violet-950/70',
                    'imagen' => '/images/helados/copa-berries.png',
                ],
            ],
        ],
        [
            'id' => 'comida',
            'titulo' => 'Comida Toppi\'s',
            'subtitulo' => 'Plato listo + bebida — productos del menú Comida Toppi\'s',
            'gradient' => 'from-orange-900/90 via-amber-950/80 to-red-950/70',
            'items' => [
                [
                    'nombre' => 'Pack Completo Toppi\'s',
                    'nombre_publico' => 'Combo completo + bebida',
                    'modalidad_label' => 'Combo · elige completo y bebida',
                    'badge' => 'Completo',
                    'descripcion_corta' => 'Completo italiano, dinámico o chacarero + bebida a elección.',
                    'gradient' => 'from-yellow-700/90 via-amber-800/80 to-orange-900/70',
                    'imagen' => '/images/salada/completo.png',
                ],
                [
                    'nombre' => 'Pack Chorrillana Toppi\'s',
                    'nombre_publico' => 'Combo chorrillana + bebida',
                    'modalidad_label' => 'Pack abierto · tamaño + carnes + Toppi\'s + bebida',
                    'badge' => 'Para compartir',
                    'descripcion_corta' => 'Tamaño papas + carnes + 13 Toppi\'s extra + bebida — precio suma visible.',
                    'gradient' => 'from-red-800/90 via-rose-900/80 to-amber-950/70',
                    'imagen' => '/images/salada/chorrillana.png',
                ],
                [
                    'nombre' => 'Combo Familiar Chorrillana + 2 Copas Toppi\'s',
                    'nombre_publico' => 'Combo familiar · chorrillana + 2 copas yogurt',
                    'modalidad_label' => 'Facebook · XL + 2 copas a elección',
                    'badge' => 'Estrella',
                    'destacado' => true,
                    'descripcion_corta' => 'Chorrillana XL + 2 copas Biscoff, Tropical o Berries. Desde $24.990.',
                    'gradient' => 'from-red-800/90 via-fuchsia-900/80 to-amber-950/70',
                    'imagen' => '/images/salada/chorrillana.png',
                ],
                [
                    'nombre' => 'Pack Papas Toppi\'s',
                    'nombre_publico' => 'Combo papas + bebida',
                    'modalidad_label' => 'Combo · elige papas y bebida',
                    'badge' => 'Snack',
                    'descripcion_corta' => 'Salchipapas o papas con queso + bebida.',
                    'gradient' => 'from-amber-700/90 via-orange-800/80 to-red-900/70',
                    'imagen' => '/images/salada/base-salada.png',
                ],
                [
                    'nombre' => 'Pack Almuerzo + Helado Toppi\'s',
                    'nombre_publico' => 'Almuerzo + helado postre',
                    'modalidad_label' => 'Combo · plato, bebida y yogurt',
                    'badge' => 'Almuerzo',
                    'descripcion_corta' => 'Plato salado + bebida + yogurt de postre a elección.',
                    'gradient' => 'from-emerald-800/90 via-teal-900/80 to-amber-950/70',
                    'imagen' => '/images/salada/wok.png',
                ],
                [
                    'nombre' => 'Pack Familiar Toppi\'s',
                    'nombre_publico' => 'Combo familiar Toppi\'s',
                    'modalidad_label' => 'Combo familiar · Mega + yogurt + bebida',
                    'badge' => 'Familiar',
                    'descripcion_corta' => 'Chorrillana Mega + helado yogurt familiar + bebida grande.',
                    'gradient' => 'from-violet-900/90 via-purple-950/80 to-fuchsia-950/70',
                    'imagen' => '/images/helados/yogen-mix.png',
                ],
            ],
        ],
        [
            'id' => 'regalos',
            'titulo' => 'Canastas y regalos',
            'subtitulo' => 'Productos sueltos del minimarket + empaque — tú eliges bebidas y dulces',
            'gradient' => 'from-rose-900/90 via-pink-950/80 to-violet-950/70',
            'items' => [
                [
                    'nombre' => 'Pack Desayuno Sorpresa',
                    'nombre_publico' => 'Canasta desayuno sorpresa',
                    'modalidad_label' => 'Canasta personalizable · empaque incluido',
                    'badge' => 'Desayuno',
                    'ocasion' => 'desayuno',
                    'tarjeta_personalizable' => true,
                    'descripcion_corta' => 'Caja, papel seda, cinta y sticker + tú eliges bebida caliente y dulce.',
                    'gradient' => 'from-rose-800/90 via-pink-900/80 to-violet-950/70',
                    'imagen' => '/images/regalos/pack-desayuno-clasico.png',
                ],
                [
                    'nombre' => 'Pack Once Completa',
                    'nombre_publico' => 'Canasta once completa',
                    'modalidad_label' => 'Canasta personalizable · canasto incluido',
                    'badge' => 'Once',
                    'ocasion' => 'once',
                    'tarjeta_personalizable' => true,
                    'descripcion_corta' => 'Canasto mimbre + relleno + bebida y dulces a elección.',
                    'gradient' => 'from-amber-700/90 via-orange-800/80 to-rose-900/70',
                    'imagen' => '/images/regalos/pack-once-familiar.png',
                ],
                [
                    'nombre' => 'Regalo Cumpleaños — Desayuno Sorpresa',
                    'nombre_publico' => 'Regalo cumpleaños — desayuno sorpresa',
                    'modalidad_label' => 'Canasta personalizable · globo incluido',
                    'badge' => 'Cumpleaños',
                    'ocasion' => 'cumpleanos',
                    'tarjeta_personalizable' => true,
                    'descripcion_corta' => 'Globo + caja regalo + bebida, dulce y helado yogurt postre.',
                    'gradient' => 'from-fuchsia-800/90 via-rose-900/80 to-violet-950/70',
                    'imagen' => '/images/regalos/pack-cumpleanos-dulce.png',
                ],
                [
                    'nombre' => 'Regalo de Pareja — Tarde Dulce',
                    'nombre_publico' => 'Regalo pareja — tarde dulce',
                    'modalidad_label' => 'Canasta personalizable · 2 helados artesanales',
                    'badge' => 'Amor',
                    'ocasion' => 'amor',
                    'tarjeta_personalizable' => true,
                    'descripcion_corta' => 'Dos artesanales + bebida + chocolates opcionales + empaque regalo.',
                    'gradient' => 'from-rose-700/90 via-red-900/80 to-pink-950/70',
                    'imagen' => '/images/regalos/pack-amor-espumante.png',
                ],
                [
                    'nombre' => 'Pack Condolencias — Detalle Sobrio',
                    'nombre_publico' => 'Detalle condolencias',
                    'modalidad_label' => 'Canasta sobria · empaque incluido',
                    'badge' => 'Condolencias',
                    'ocasion' => 'condolencias',
                    'tarjeta_personalizable' => true,
                    'descripcion_corta' => 'Caja regalo + crackers + bebida a elección. Armado con respeto.',
                    'gradient' => 'from-stone-700/90 via-stone-900/80 to-slate-950/70',
                    'imagen' => '/images/regalos/pack-condolencias.png',
                ],
                [
                    'nombre' => 'Regalo Helado Toppi\'s — Para Ti',
                    'nombre_publico' => 'Gift card helado Toppi\'s',
                    'modalidad_label' => 'Regalo personalizable · elige base y toppings',
                    'badge' => 'Gift',
                    'ocasion' => 'gift',
                    'tarjeta_personalizable' => true,
                    'descripcion_corta' => 'Tarjeta saludo + dulce incluido + helado a elección del receptor.',
                    'gradient' => 'from-cyan-800/90 via-teal-900/80 to-emerald-950/70',
                    'imagen' => '/images/helados/copa-tropical.png',
                ],
            ],
        ],
    ],
];
