<?php

/**
 * Perfiles del armador web (ProductBuilderModal) y reglas de copy/orden.
 * Editable sin tocar el frontend — la API expone builder_meta y step_title/hint por grupo.
 */
return [
    'auto_detect' => [
        'helado_arma_name' => "Helado Toppi's",
        'helado_soft_name' => "Soft Toppi's",
        'helado_artesanal_name' => "Artesanal Toppi's",
    ],

    'profiles' => [
        'auto' => [
            'label' => 'Automático',
            'description' => 'Detecta el perfil por nombre, categoría y tipo de pack.',
        ],
        'generic' => [
            'label' => 'Genérico',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
        ],
        'helado_arma' => [
            'label' => 'Helado · arma el tuyo',
            'display_title' => 'Arma tu helado',
            'line_label' => 'Arma tu helado',
            'is_regalo' => false,
            'is_helado_builder' => true,
            'is_helado_experience' => true,
            'helado_arma_tipo_step' => true,
            'group_sort_mode' => 'helado_arma',
            'hide_combo_suggestions' => false,
        ],
        'helado_soft' => [
            'label' => 'Helado soft',
            'display_title' => 'Helado soft',
            'line_label' => 'Helado soft',
            'is_regalo' => false,
            'is_helado_builder' => true,
            'is_helado_experience' => true,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
            'default_radio' => [
                [
                    'group_match' => ['cono', 'tamaño', 'tamano'],
                    'sku_contains' => 'CONO-1',
                    'nombre_contains' => '$1.000',
                ],
            ],
        ],
        'helado_artesanal' => [
            'label' => 'Helado artesanal',
            'display_title' => 'Helado artesanal',
            'line_label' => 'Helado artesanal',
            'is_regalo' => false,
            'is_helado_builder' => true,
            'is_helado_experience' => true,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
            'default_radio' => [
                [
                    'group_match' => ['porción', 'porcion', 'bola'],
                    'sku_contains' => 'BOLA-1',
                    'nombre_contains' => '1 bola',
                ],
            ],
        ],
        'helado_yogen' => [
            'label' => 'Helado de yogurt',
            'display_title' => 'Helado de yogurt',
            'line_label' => 'Helado de yogurt',
            'is_regalo' => false,
            'is_helado_builder' => true,
            'is_helado_experience' => true,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
        ],
        'helado_combo' => [
            'label' => 'Pack cerrado · menú (helado)',
            'display_title' => null,
            'line_label' => 'Pack cerrado · todo incluido',
            'is_regalo' => false,
            'is_helado_builder' => true,
            'is_helado_experience' => true,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => true,
        ],
        'salada_base' => [
            'label' => 'Salada · base',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
        ],
        'salada_chorrillana' => [
            'label' => 'Chorrillana',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
        ],
        'salada_wok' => [
            'label' => 'Wok / bowl',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
        ],
        'salada_sandwich' => [
            'label' => 'Sandwich / completo',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => false,
        ],
        'jh_autoservicio' => [
            'label' => 'JobsHours · Paquete modular',
            'display_title' => 'Arma tu paquete paso a paso',
            'line_label' => 'Tu paquete JobsHours',
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'is_jobs_hours_builder' => true,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => true,
            'modal_subtitle' => 'Oferta avanzada · elige plan e implementación · hardware opcional al final',
            'customize_title' => 'Datos de tu negocio',
            'add_to_cart_label' => 'Agregar y pagar',
            'default_radio' => [
                [
                    'group_match' => ['plan mensual'],
                    'sku_contains' => 'JH-INT-MRR-29990',
                ],
                [
                    'group_match' => ['implementación'],
                    'sku_contains' => 'JH-INT-IMP-0',
                ],
            ],
        ],
        'jh_plan' => [
            'label' => 'JobsHours · Plan',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => true,
        ],
        'jh_servicio' => [
            'label' => 'JobsHours · Servicio',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => true,
        ],
        'jh_guia' => [
            'label' => 'JobsHours · Guía',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => false,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'hide_combo_suggestions' => true,
            'add_to_cart_label' => 'Agregar al pedido',
        ],
        'regalo' => [
            'label' => 'Pack regalo',
            'display_title' => null,
            'line_label' => null,
            'is_regalo' => true,
            'is_helado_builder' => false,
            'is_helado_experience' => false,
            'helado_arma_tipo_step' => false,
            'group_sort_mode' => 'db',
            'modal_subtitle' => 'Diseña tu regalo paso a paso',
            'customize_title' => 'Personaliza tu regalo',
            'add_to_cart_label' => 'Agregar regalo al pedido',
            'hide_combo_suggestions' => false,
        ],
    ],

    /**
     * Orden legacy por nombre de grupo (fallback si sort_order no está configurado).
     */
    'group_sort_fallback' => [
        'default' => [
            ['match' => ['sabor yogurt', 'base yogurt', 'tipo y sabor'], 'order' => 5],
            ['match' => ['fruta'], 'order' => 15],
            ['match' => ['tamaño', 'tamano'], 'order' => 20],
            ['match' => ['crocante', 'topping ligero'], 'order' => 25],
            ['match' => ['tu base', 'elige tu bebida', 'tipo de pan', 'elige tu dulce', 'cecina', 'untable', 'queso laminado', 'carbohidrato', 'proteína', 'proteina', 'verdura'], 'order' => 10],
            ['match' => ['tamaño papas', 'carnes incluidas'], 'order' => 12],
            ['match' => ['tipo de chorrillana', 'tipo de'], 'order' => 15],
            ['match' => ['proteína', 'proteina'], 'order' => 20],
            ['match' => ['porción', 'porcion'], 'order' => 25],
            ['match' => ['salsa incluida'], 'order' => 30],
            ['match' => ['salsa'], 'order' => 30, 'exclude' => ["toppi's"]],
            ['match' => ['extra', "toppi's", 'toppi'], 'order' => 90],
        ],
        'helado_arma' => [
            ['match' => ['tamaño', 'tamano'], 'order' => 30],
            ['match' => ['salsa'], 'order' => 40],
            ['match' => ['fruta'], 'order' => 50],
            ['match' => ['crocante'], 'order' => 60],
            ['match' => ['premium'], 'order' => 70],
        ],
    ],

    /**
     * Reglas de título/hint por paso. Primera coincidencia gana.
     * profiles: null = cualquier perfil.
     */
    'group_step_rules' => [
        ['profiles' => ['salada_base'], 'group_match' => ['tu base'], 'input_type' => 'radio', 'title' => 'Tu base', 'hint' => 'Papas, tortilla, tallarines o arroz — precio final por opción'],
        ['profiles' => ['salada_base'], 'group_match' => ['porción', 'porcion'], 'input_type' => 'radio', 'title' => 'Tamaño', 'hint' => 'Personal o familiar para compartir'],
        ['profiles' => ['salada_chorrillana'], 'group_match' => ['tamaño papas'], 'input_type' => 'radio', 'title' => 'Tamaño papas', 'hint' => 'Compartir incluido · XL, familiar o Mega suman al total'],
        ['profiles' => ['salada_chorrillana'], 'group_match' => ['carnes incluidas'], 'input_type' => 'radio', 'title' => 'Carnes', 'hint' => 'Clásica con 2 vienasas · sube ticket con más carnes'],
        ['profiles' => ['salada_chorrillana'], 'group_match' => ['toppi\'s extra', 'toppi extra'], 'input_type' => 'checkbox', 'title' => 'Toppi\'s extra', 'hint' => 'Opcional · marca todos los que quieras · cada uno suma al total'],
        ['profiles' => ['salada_chorrillana'], 'group_match' => ['complementos', 'compartir'], 'input_type' => 'checkbox', 'title' => 'Complementos', 'hint' => 'Opcional · jarra jugo o 2 completos · suman al total'],
        ['profiles' => ['salada_chorrillana'], 'group_match' => ['copa yogurt 1', 'copa yogurt 2'], 'input_type' => 'radio', 'title' => 'Copa yogurt', 'hint' => 'Elige 1 por copa — incluida en el combo familiar'],
        ['profiles' => null, 'group_match' => ['tipo de chorrillana'], 'input_type' => 'radio', 'title' => 'Tipo de chorrillana', 'hint' => 'Clásica al precio base · recetas especiales con total visible'],
        ['profiles' => ['salada_wok'], 'group_match' => ['tu base'], 'input_type' => 'radio', 'title' => 'Base del bowl', 'hint' => 'Arroz, chaufa o fideos de arroz'],
        ['profiles' => null, 'group_match' => ['proteína', 'proteina'], 'input_type' => 'radio', 'title' => 'Proteína', 'hint' => 'Pollo, cerdo agridulce o camarón'],
        ['profiles' => ['salada_wok'], 'group_match' => ['salsa'], 'input_type' => 'radio', 'title' => 'Salsa wok', 'hint' => 'Swicy, teriyaki o soja y ajo'],
        ['profiles' => ['helado_yogen', 'helado_combo'], 'group_match' => ['salsa incluida', 'salsa'], 'input_type' => 'radio', 'title' => 'Salsa dulce', 'hint' => 'Chocolate, manjar o frutilla — incluida en tu pedido'],
        ['profiles' => ['helado_soft'], 'group_match' => ['sabor soft', 'soft de la máquina', 'sabor'], 'input_type' => 'radio', 'exclude_group' => ['cono'], 'title' => 'Elige sabor', 'hint' => 'Vainilla, chocolate o sabor mixto'],
        ['profiles' => ['helado_soft'], 'group_match' => ['cono', 'tamaño', 'tamano'], 'input_type' => 'radio', 'title' => 'Elige tamaño', 'hint' => 'Misma porción de helado · cambia solo el cono'],
        ['profiles' => ['helado_artesanal'], 'group_match' => ['sabor artesanal', 'sabor'], 'input_type' => 'radio', 'title' => 'Elige sabor', 'hint' => 'Cremoso e intenso'],
        ['profiles' => ['helado_artesanal'], 'group_match' => ['porción', 'porcion', 'bola'], 'input_type' => 'radio', 'title' => 'Cuántas bolas', 'hint' => '1 bola $2.000 · 2 bolas $3.500'],
        ['profiles' => ['helado_yogen'], 'group_match' => ['sabor yogurt', 'base yogurt', 'sabor'], 'input_type' => 'radio', 'title' => 'Sabor de yogurt', 'hint' => 'Elige tu base'],
        ['profiles' => ['helado_yogen'], 'group_match' => ['fruta'], 'input_type' => 'radio', 'title' => 'Fruta', 'hint' => 'Incluida en tu helado'],
        ['profiles' => ['helado_combo'], 'group_match' => ['fruta'], 'input_type' => 'radio', 'title' => 'Fruta', 'hint' => 'Ya incluido en tu combo'],
        ['profiles' => ['helado_combo'], 'group_match' => ['crocante', 'topping'], 'input_type' => 'radio', 'title' => 'Topping', 'hint' => 'Ya incluido en tu combo'],
        ['profiles' => ['helado_combo'], 'group_match' => ['sabor'], 'input_type' => 'radio', 'title' => 'Sabor', 'hint' => 'Ya incluido en tu combo'],
        ['profiles' => ['helado_combo'], 'group_match' => ['salsa'], 'input_type' => 'radio', 'title' => 'Salsa dulce', 'hint' => 'Incluida — chocolate, manjar o frutilla'],
        ['profiles' => ['helado_arma', 'helado_soft', 'helado_artesanal'], 'group_match' => ['tamaño', 'tamano'], 'input_type' => 'radio', 'title' => 'Tamaño', 'hint' => 'Copa simple incluida · puedes subir de tamaño'],
        ['profiles' => ['helado_arma', 'helado_soft', 'helado_artesanal'], 'group_match' => ['salsa'], 'input_type' => 'checkbox', 'title' => 'Salsas', 'hint' => 'Opcional · +$300 c/u'],
        ['profiles' => ['helado_arma', 'helado_soft', 'helado_artesanal'], 'group_match' => ['extra', "toppi's", 'toppi'], 'input_type' => 'checkbox', 'title' => 'Extras', 'hint' => 'Opcional · maní, galleta o Nutella'],
        ['profiles' => ['helado_arma', 'helado_soft', 'helado_artesanal'], 'group_match' => ['fruta'], 'input_type' => 'checkbox', 'title' => 'Fruta extra', 'hint' => 'Opcional'],
        ['profiles' => ['helado_arma', 'helado_soft', 'helado_artesanal'], 'group_match' => ['crocante'], 'input_type' => 'checkbox', 'title' => 'Crocante', 'hint' => 'Opcional'],
        ['profiles' => ['jh_autoservicio'], 'group_match' => ['plan mensual'], 'input_type' => 'radio', 'title' => 'Paso 1 · Plan mensual', 'hint' => 'Obligatorio. Elige el software base. Puedes subir de plan después.'],
        ['profiles' => ['jh_autoservicio'], 'group_match' => ['implementación'], 'input_type' => 'radio', 'title' => 'Paso 2 · Implementación', 'hint' => '¿Necesitas que te instalemos? Si ya tienes tablet y Point, elige «Solo activación» y ahorras.'],
        ['profiles' => ['jh_autoservicio'], 'group_match' => ['complemento'], 'input_type' => 'checkbox', 'title' => 'Paso 3 · Extras software', 'hint' => 'Opcional. Capacitación extra o más ítems en el menú.'],
        ['profiles' => ['jh_autoservicio'], 'group_match' => ['terminal'], 'input_type' => 'radio', 'title' => 'Paso 4 · Tu terminal Point (opcional)', 'hint' => 'Solo orientación: JobsHours no vende el equipo. Indícanos si ya lo tienes o qué comprarás.'],
        ['profiles' => ['jh_autoservicio'], 'group_match' => ['equipo'], 'input_type' => 'radio', 'title' => 'Paso 5 · Tu pantalla (opcional)', 'hint' => 'Tablet, PC o guía de compra. Puedes omitir si ya sabes qué usarás.'],
        ['profiles' => ['helado_arma', 'helado_soft', 'helado_artesanal'], 'group_match' => ['premium'], 'input_type' => 'checkbox', 'title' => 'Premium', 'hint' => 'Opcional'],
        ['profiles' => null, 'group_match' => ['sabor yogurt', 'base yogurt'], 'input_type' => 'radio', 'title' => 'Sabor', 'hint' => 'Helado de yogurt con fruta'],
        ['profiles' => null, 'group_match' => ['fruta'], 'input_type' => 'radio', 'title' => 'Fruta real', 'hint' => 'Elige la fruta de tu mix'],
        ['profiles' => null, 'group_match' => ['tamaño', 'tamano'], 'input_type' => 'radio', 'title' => 'Tamaño', 'hint' => 'Copa mediana incluida en el precio base'],
        ['profiles' => null, 'group_match' => ['crocante', 'topping ligero'], 'input_type' => 'radio', 'title' => null, 'hint' => 'Incluido en tu combo', 'use_group_name' => true],
        ['profiles' => null, 'group_match' => ['elige tu bebida', 'bebida'], 'input_type' => 'radio', 'title' => 'Bebida', 'hint' => 'Café o té sin extra · jugo con precio final'],
        ['profiles' => null, 'group_match' => ['tipo de pan'], 'input_type' => 'radio', 'title' => 'Pan', 'hint' => 'Hallulla o marraqueta — mismo precio del pack'],
        ['profiles' => ['regalo'], 'group_match' => ['cecina', 'fiambre', 'jamón', 'jamon'], 'input_type' => 'radio', 'title' => 'Cecina', 'hint' => 'Jamón, mortadela o salchichón laminado al vacío — incluido en tu once'],
        ['profiles' => ['regalo'], 'group_match' => ['carbohidrato'], 'input_type' => 'radio', 'title' => 'Base', 'hint' => 'Arroz o fideos — elige uno para cocinar'],
        ['profiles' => ['regalo'], 'group_match' => ['proteína', 'proteina'], 'input_type' => 'radio', 'title' => 'Proteína', 'hint' => 'Huevos, queso, jamón o pieza de carne al vacío'],
        ['profiles' => ['regalo'], 'group_match' => ['pieza de carne', 'piezas de carne'], 'input_type' => 'radio', 'title' => 'Carne', 'hint' => 'Molida, pollo, posta, chuleta o costillar — al vacío'],
        ['profiles' => ['regalo'], 'group_match' => ['verdura'], 'input_type' => 'radio', 'title' => 'Verdura', 'hint' => 'Fresca del día — cebolla, tomate o papa'],
        ['profiles' => ['regalo'], 'group_match' => ['verduras para cocinar'], 'input_type' => 'checkbox', 'title' => 'Verduras', 'hint' => 'Marca 2 o más para tu olla o guiso'],
        ['profiles' => ['regalo'], 'group_match' => ['queso laminado', 'queso'], 'input_type' => 'radio', 'title' => 'Queso', 'hint' => 'Queso laminado incluido en el pack once'],
        ['profiles' => ['regalo'], 'group_match' => ['untable'], 'input_type' => 'radio', 'title' => 'Untable', 'hint' => 'Mermelada, manjar, palta o mantequilla — elige uno'],
        ['profiles' => null, 'group_match' => ['elige tu dulce', 'dulce'], 'input_type' => 'radio', 'title' => 'Dulce', 'hint' => 'Mermelada incluida · manjar o Nutella con total claro'],
        ['profiles' => ['salada_sandwich'], 'group_match' => ['extra', "toppi's", 'toppi'], 'input_type' => 'checkbox', 'title' => "Toppi's", 'hint' => 'Opcional — suma al total del pedido'],
        ['profiles' => null, 'group_match' => ['extra', "toppi's", 'toppi'], 'input_type' => 'checkbox', 'title' => 'Extras', 'hint' => 'Opcional — suma al total del pedido'],
    ],

    /** Picker de tipo helado (paso «arma el tuyo») — expuesto en builder_meta.helado_type_meta */
    'helado_type_meta' => [
        'soft' => [
            'label' => 'Helado soft',
            'hint' => 'Cono $1.000 · grande $1.800',
            'extra' => 0,
            'tier' => 'Entrada',
            'benefit' => 'Vainilla, chocolate o mixto',
            'sku_match' => 'TOPPI-SOFT',
            'nombre_prefix' => 'soft ',
        ],
        'yogurt' => [
            'label' => 'Helado de yogurt',
            'hint' => 'Con fruta · desde $2.800',
            'extra' => 300,
            'tier' => 'Equilibrado',
            'benefit' => 'Fresco con fruta real',
            'sku_match' => 'TOPPI-YOG',
            'nombre_prefix' => 'yogurt ',
        ],
        'artesanal' => [
            'label' => 'Helado artesanal',
            'hint' => '1 bola $2.000 · 2 bolas $3.500',
            'extra' => 800,
            'tier' => 'Premium',
            'benefit' => 'Cremoso en bolas',
            'sku_match' => 'TOPPI-ART',
            'nombre_prefix' => 'artesanal ',
        ],
    ],
];
