<?php

/**
 * Packs y regalos personalizables — portada y /regalos en dondemorales.cl
 * Todos los packs destacados abren ProductBuilderModal (opciones + campos propios).
 */
return [
    'title' => 'Arma tu regalo Toppi\'s',
    'tagline' => 'Tu ocasión + tu mensaje — productos reales del local',
    'subtitle' => 'Pack listo o personalizable · envío gratis regalo en Renaico · retiro Santiago Watt 205, Renaico',

    'mensaje_personalizable' => 'Reserva online: eliges, pagas y lo armamos antes de tu retiro en Santiago Watt 205, Renaico. Imagen referencial — «Incluye» es lo que recibes.',

    'ocasiones' => [
        ['id' => 'todos', 'label' => 'Todos'],
        ['id' => 'desayuno', 'label' => 'Desayuno'],
        ['id' => 'cumpleanos', 'label' => 'Cumpleaños'],
        ['id' => 'para_mama', 'label' => 'Para mamá'],
        ['id' => 'amor', 'label' => 'Amor'],
        ['id' => 'condolencias', 'label' => 'Condolencias'],
        ['id' => 'corporativo', 'label' => 'Corporativo'],
        ['id' => 'impulso', 'label' => 'Detalle rápido'],
    ],

    'corporativo' => [
        'titulo' => 'Regalo corporativo · empresas Araucanía',
        'subtitulo' => 'Plantas, agrícola, colegios — armamos pedidos de 10+ unidades con sticker logo.',
        'nombre_pack' => 'Pack Corporativo (B2B)',
        'precio_10_mas' => 9990,
        'precio_unidad' => 12990,
        'imagen' => '/images/regalos/pack-corporativo.png',
        'whatsapp_prefill' => 'Hola, quiero cotizar packs corporativos DondeMorales. Cantidad: ___ · Fecha entrega: ___ · Empresa: ___',
    ],

    'confianza' => [
        ['icon' => 'shield', 'texto' => 'Pago seguro Mercado Pago / Flow'],
        ['icon' => 'truck', 'texto' => 'Envío gratis packs regalo en Renaico'],
        ['icon' => 'calendar', 'texto' => 'Reserva 24 h — armado en Santiago Watt 205, Renaico'],
        ['icon' => 'gift', 'texto' => 'Tarjeta de saludo incluida · foto referencial del pack'],
    ],

    'flujo' => [
        ['paso' => 1, 'titulo' => 'Revisa qué incluye', 'texto' => 'Lista fija de productos y empaque — sin adivinar'],
        ['paso' => 2, 'titulo' => 'Reserva y paga', 'texto' => 'Fecha de retiro + pago online seguro'],
        ['paso' => 3, 'titulo' => 'Lo armamos', 'texto' => 'Descontamos stock real antes de tu llegada'],
    ],

    'destacados' => [
        [
            'nombre' => 'Piezas de Carne DondeMorales',
            'badge' => 'Carnes',
            'concepto' => 'Al vacío',
            'descripcion_corta' => 'Molida, pollo, posta, chuleta o costillar · opcional verdura para la olla.',
            'gradient' => 'from-red-800/90 via-rose-950/80 to-stone-950/70',
            'imagen' => '/images/regalos/pack-carne-dm.png',
        ],
        [
            'nombre' => 'Base Cocina DondeMorales',
            'badge' => 'Cocinar',
            'concepto' => 'Arroz o fideos + verduras',
            'descripcion_corta' => 'Aceite y huevos incluidos · elige carbohidrato y 2+ verduras · proteína opcional.',
            'gradient' => 'from-emerald-700/90 via-teal-900/80 to-slate-950/70',
            'imagen' => '/images/regalos/pack-cocina-dm.png',
        ],
        [
            'nombre' => 'Cena DondeMorales',
            'badge' => 'Cena',
            'concepto' => 'Plato simple',
            'descripcion_corta' => 'Arroz o fideos + huevos, queso, jamón o pieza de carne + verdura.',
            'gradient' => 'from-indigo-800/90 via-slate-900/80 to-violet-950/70',
            'imagen' => '/images/regalos/pack-cena-dm.png',
        ],
        [
            'nombre' => 'Verduras DondeMorales',
            'badge' => 'Verduras',
            'concepto' => 'Surtido fijo',
            'descripcion_corta' => 'Cebolla, tomate, papa y zanahoria — listo para cocinar.',
            'gradient' => 'from-green-700/90 via-lime-900/80 to-emerald-950/70',
            'imagen' => '/images/regalos/pack-verduras-dm.png',
        ],
        [
            'nombre' => 'Desayuno DondeMorales',
            'badge' => 'Desayuno',
            'concepto' => 'Pan + bebida',
            'descripcion_corta' => 'Marraqueta u hallulla · café, té, leche o jugo · mermelada, manjar o palta.',
            'gradient' => 'from-amber-600/90 via-orange-800/80 to-yellow-900/70',
            'imagen' => '/images/regalos/pack-desayuno-dm.png',
        ],
        [
            'nombre' => 'Once DondeMorales',
            'badge' => 'Once',
            'concepto' => 'Pan + cecina + queso',
            'descripcion_corta' => 'Marraqueta u hallulla · jamón, mortadela o salchichón al vacío · queso · té o café.',
            'gradient' => 'from-amber-700/90 via-orange-800/80 to-rose-900/70',
            'imagen' => '/images/regalos/pack-once-dm.png',
        ],
        [
            'nombre' => 'Pack Desayuno Clásico',
            'badge' => 'Regalo',
            'ocasion' => 'desayuno',
            'modalidad_label' => 'Pack cerrado · contenido fijo',
            'concepto' => '$12.990',
            'descripcion_corta' => 'Marraquetas, café, mermelada y empaque regalo completo. Lo que ves en “Incluye” es lo que recibes.',
            'gradient' => 'from-rose-800/90 via-pink-900/80 to-violet-950/70',
            'imagen' => '/images/regalos/pack-desayuno-clasico.png',
        ],
        [
            'nombre' => 'Pack Cumpleaños para Mamá',
            'badge' => 'Para mamá',
            'ocasion' => 'para_mama',
            'modalidad_label' => 'Pack cerrado · contenido fijo',
            'concepto' => '$19.990',
            'descripcion_corta' => 'Cumpleaños, detalle o “solo porque” — globo, Ferrero, jugo, té, muffin y empaque regalo.',
            'gradient' => 'from-pink-700/90 via-rose-900/80 to-violet-950/70',
            'imagen' => '/images/regalos/pack-cumpleanos-dulce.png',
        ],
        [
            'nombre' => 'Pack Cumpleaños Dulce',
            'badge' => 'Cumpleaños',
            'ocasion' => 'cumpleanos',
            'concepto' => '$15.990',
            'descripcion_corta' => 'Globo + Ferrero + dulces + empaque festivo.',
            'gradient' => 'from-fuchsia-700/90 via-purple-900/80 to-violet-950/70',
            'imagen' => '/images/regalos/pack-cumpleanos-dulce.png',
        ],
        [
            'nombre' => 'Pack Amor & Espumante',
            'badge' => 'Amor',
            'ocasion' => 'amor',
            'concepto' => '$24.990',
            'descripcion_corta' => 'Espumante + chocolates + detalle romántico.',
            'gradient' => 'from-rose-700/90 via-red-900/80 to-pink-950/70',
            'imagen' => '/images/regalos/pack-amor-espumante.png',
        ],
        [
            'nombre' => 'Pack Once Familiar',
            'badge' => 'Once',
            'ocasion' => 'once',
            'concepto' => '$19.990',
            'descripcion_corta' => 'Canasto + salados y dulces para compartir.',
            'gradient' => 'from-amber-700/90 via-orange-800/80 to-rose-900/70',
            'imagen' => '/images/regalos/pack-once-familiar.png',
        ],
        [
            'nombre' => 'Pack Papá Completo',
            'badge' => '19 jun',
            'modalidad_label' => 'Pack cerrado · 13 ítems',
            'concepto' => '$16.990',
            'descripcion_corta' => 'Desayuno con palta en envase plástico, jamón, queso, pan, jugo, dulces y empaque regalo.',
            'gradient' => 'from-slate-700/90 via-blue-900/80 to-indigo-950/70',
            'imagen' => '/images/regalos/pack-papa-completo.png',
        ],
        [
            'nombre' => 'Pack Papá Premium',
            'badge' => 'Más vendido',
            'modalidad_label' => 'Pack cerrado · 17 ítems',
            'concepto' => '$21.990',
            'descripcion_corta' => 'Completo + palta en envase plástico + Ferrero + globo + postre. El más pedido.',
            'gradient' => 'from-amber-700/90 via-orange-900/80 to-slate-950/70',
            'imagen' => '/images/regalos/pack-papa-premium.png',
        ],
        [
            'nombre' => 'Pack Papá Bandeja',
            'badge' => 'Bandeja',
            'modalidad_label' => 'Pack cerrado · canasto',
            'concepto' => '$24.990',
            'descripcion_corta' => 'Canasto abundante con picoteo, bebidas, pan, dulces y globo.',
            'gradient' => 'from-emerald-700/90 via-teal-900/80 to-slate-950/70',
            'imagen' => '/images/regalos/pack-papa-bandeja.png',
        ],
        [
            'nombre' => 'Pack Corporativo (B2B)',
            'badge' => 'Empresa',
            'ocasion' => 'corporativo',
            'modalidad_label' => 'Pack cerrado · mínimo 10 u.',
            'concepto' => 'desde $9.990 c/u',
            'descripcion_corta' => 'Café + galletas + bolsa kraft con sticker — cotiza volumen por WhatsApp.',
            'gradient' => 'from-emerald-800/90 via-teal-950/80 to-slate-950/70',
            'imagen' => '/images/regalos/pack-corporativo.png',
        ],
        [
            'nombre' => 'Regalo Helado Toppi\'s — Para Ti',
            'badge' => 'Gift',
            'ocasion' => 'impulso',
            'concepto' => '$9.990',
            'descripcion_corta' => 'Tarjeta + dulce + helado a elección — detalle rápido, retiro hoy.',
            'gradient' => 'from-cyan-800/90 via-teal-900/80 to-emerald-950/70',
            'imagen' => '/images/helados/copa-tropical.png',
        ],
    ],

    'categorias_nombres' => [
        'Regalos y Ocasiones',
        'Empaque y regalo',
    ],
];
